<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.538">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hafizd Razaan Zaidan (220204128)">
<meta name="dcterms.date" content="2024-01-15">

<title>Dampak Ekspor Dan Impor Jagung Terhadap Produktivitas Jagung Di Sumatera Barat</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Dampak Ekspor Dan Impor Jagung Terhadap Produktivitas Jagung Di Sumatera Barat</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hafizd Razaan Zaidan (220204128) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 15, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>Politeknik APP Jakarta</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Indonesia, yang merupakan negara agraris di Asia, dikenal karena produksi komoditas pertaniannya yang melimpah seperti sayuran dan buah-buahan. Sebagian besar penduduknya menggantungkan hidup pada pertanian, didukung oleh sumber daya alam yang kaya yang berkontribusi signifikan terhadap kebutuhan domestik dan perekonomian negara. Sektor pertanian memainkan peran penting dalam pembangunan Indonesia, terlihat dari kontribusinya terhadap pertumbuhan Produk Domestik Bruto (PDB). Selain itu, pertanian berfungsi sebagai sumber utama lapangan kerja, pendapatan bagi penduduk, pengentasan kemiskinan, penerimaan devisa, dan berperan penting dalam sektor pembangunan lainnya.</p>
<p>Di antara berbagai produk pertanian, jagung menjadi salah satu komoditas utama setelah padi dan dianggap sebagai pengganti potensial untuk beras sebagai pangan pokok. Jagung memiliki nilai strategis dan ekonomis, berperan sebagai sumber utama karbohidrat dan protein, serta bahan baku industri. Menurut Kementerian Pertanian, jagung memiliki empat fungsi (4F): pangan, pakan, bahan bakar, dan bahan baku industri. Sekitar 60% jagung digunakan sebagai pakan ternak, khususnya unggas, sedangkan hanya sekitar 30% digunakan untuk konsumsi manusia, dan sisanya untuk keperluan industri dan benih. Sumatera Barat memiliki peran yang signifikan dalam sektor pertanian di Indonesia, termasuk produksi jagung sebagai salah satu komoditas utama. Jagung memiliki peranan penting dalam pemenuhan kebutuhan pangan dan kestabilan ekonomi daerah tersebut. Saat ini, perdagangan internasional semakin menjadi bagian integral dalam perekonomian global, termasuk ekspor dan impor jagung.</p>
<p>Pada satu sisi, ekspor jagung dapat membuka peluang pasar baru bagi petani di Sumatera Barat, meningkatkan pendapatan, dan memberikan kontribusi positif terhadap perekonomian daerah. Namun, di sisi lain, impor jagung dapat berpotensi mempengaruhi produktivitas lokal dengan membawa persaingan yang lebih ketat. oleh karena itu Penelitian ini diharapkan dapat memberikan wawasan mendalam mengenai interaksi kompleks antara perdagangan jagung dengan produktivitas di tingkat lokal, membantu pemerintah daerah, petani, dan pelaku industri untuk mengembangkan strategi yang berkelanjutan dan mengoptimalkan manfaat ekspor dan impor jagung bagi Sumatera Barat. Dengan demikian, latar belakang ini menjadi penting untuk merinci kerangka penelitian yang akan dilakukan dan memotivasi penelitian lebih lanjut dalam konteks hubungan antara ekspor, impor, dan produktivitas jagung di daerah ini. ### Ruang Lingkup</p>
<p>Dalam penelitian ini, peneliti memfokuskan penelitiannya pada data dari Trade Map dan Badan Pusat Statistik. Penelitian ini mencakup tiga variabel utama, yaitu nilai ekspor jagung Indonesia, nilai impor jagung Indonesia, dan nilai produktivitas jagung di Sumatera Barat. Data yang digunakan dalam penelitian ini bersifat time series, meliputi periode 2013-2022. Data ini menjadi fokus utama penelitian untuk menggali informasi dan insight terkait dengan tren dan pola yang terkait dengan ekspor jagung, impor jagung, dan produktivitas jagung di wilayah Sumatra Barat selama periode tersebut.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.2</span> Rumusan Masalah</h3>
<p>Berdasarkan pembahasan latar belakang di atas, rumusan masalah yang ditemukan adalah sebagai berikut:</p>
<ol type="1">
<li>bagaimana dampak impor jagung terhadap produktivitas jagung di Sumatera Utara</li>
<li>bagaimana dampak ekspor jagung terhadap produktivitas jagung di Sumatera Utara</li>
</ol>
</section>
<section id="tujuan-penelitian" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="tujuan-penelitian"><span class="header-section-number">1.3</span> Tujuan Penelitian</h3>
<p>Berdasarkan latar belakang dan permasalahan yang ada maka tujuan dari penelitian ini adalah untuk mengetahui dampak ekspor dan impor jagung terhadap produktivitas jagung di Sumatra Utara Dan manfaat dari penelitian ini yaitu menjadi referensi untuk menambah pengetahuan baik untuk penulis, instansi dan masyarakaat Indonesia untuk mengetahui bagaimana dampak ekspor dan impor jagung terhadap produktivitas jagung di Sumatra Barat.</p>
</section>
<section id="package" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="package"><span class="header-section-number">1.4</span> Package</h3>
<p>Packages yang digunakan sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi Pustaka</h2>
<section id="ekspor" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="ekspor"><span class="header-section-number">2.1</span> Ekspor</h3>
<p>Ekspor merujuk pada proses pengeluaran barang dari wilayah pabean Indonesia untuk dikirim ke luar negeri, sesuai dengan ketentuan peraturan kepabeanan yang berlaku, seperti yang dijelaskan oleh Marolop Tanjung (2011). Dalam konteks lain, ekspor dapat diartikan sebagai tindakan penjualan komoditas di Indonesia kepada negara lain, dengan harapan menerima pembayaran dalam mata uang asing, serta melibatkan penggunaan bahasa asing, sebagaimana dikemukakan oleh Amir M. S (2004). Menurut definisi dari Kementerian Perdagangan (Kemendag), ekspor merupakan kegiatan mengeluarkan barang dari wilayah pabean Indonesia menuju wilayah pabean negara lain. Proses ekspor dimulai dengan adanya penawaran dari salah satu pihak yang kemudian disetujui oleh pihak lain melalui kontrak penjualan, baik dari pihak eksportir maupun importir.</p>
</section>
<section id="impor" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="impor"><span class="header-section-number">2.2</span> Impor</h3>
<p>Impor merupakan proses memasukkan barang ke dalam wilayah pabean suatu negara. Berbeda dengan ekspor yang dapat meningkatkan pendapatan nasional, impor memiliki dampak penambahan pengeluaran dan penurunan pendapatan nasional suatu daerah. Sukirno (2011) menyatakan bahwa arus barang impor dapat menyebabkan keluarnya atau bocornya sebagian dari aliran pengeluaran sektor rumah tangga ke sektor perusahaan, yang pada akhirnya dapat menurunkan pendapatan nasional yang mungkin dapat dicapai. Meskipun demikian, impor juga memiliki sisi positif, yakni membantu negara memenuhi kebutuhan dalam negeri jika barang atau jasa yang diimpor tidak tersedia di negara atau daerah tersebut. Hal ini sejalan dengan konsep teori Hecksher-Ohlin yang dijelaskan oleh Appleyeard, Field, dan Cobb (2008), yang menyatakan bahwa suatu negara akan mengimpor produk atau barang yang menggunakan faktor produksi yang tidak atau jarang dimiliki oleh negara tersebut. Kegiatan ini dapat menjadi menguntungkan bagi negara tersebut dibandingkan dengan mencoba memproduksi sendiri secara tidak efisien.</p>
</section>
<section id="produktivitas" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="produktivitas"><span class="header-section-number">2.3</span> Produktivitas</h3>
<p>Menurut Busro (2018), Hasibuan menyatakan bahwa produktivitas adalah perbandingan antara hasil (output) dan masukan (input). Peningkatan produktivitas dianggap dapat meningkatkan efisiensi dalam hal waktu, bahan, dan tenaga, serta meningkatkan sistem kerja, teknik produksi, dan keterampilan tenaga kerja. Dalam pandangan Handoko, juga dikutip oleh Busro (2018), produktivitas dipahami sebagai sikap mental dan upaya manusia untuk mencapai hasil yang lebih baik dengan menggunakan sumber daya seefektif mungkin, yang akhirnya diukur dengan masukan yang digunakan untuk mencapai hasil optimal.</p>
</section>
<section id="komoditi-jagung" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="komoditi-jagung"><span class="header-section-number">2.4</span> Komoditi Jagung</h3>
<p>Jagung (Zea mays L.) adalah salah satu tanaman pangan yang memiliki signifikansi penting, sejajar dengan gandum dan padi. Di Amerika Tengah dan Selatan, jagung berfungsi sebagai sumber utama karbohidrat dan menjadi alternatif pangan utama di Amerika Serikat. Beberapa komunitas di Indonesia, seperti di Madura dan Nusa Tenggara, juga mengandalkan jagung sebagai makanan pokok. Selain itu, jagung memiliki beragam penggunaan, termasuk sebagai pakan ternak, bahan dasar pembuatan minyak, tepung jagung (maizena) dari biji jagung, dan bahan baku untuk industri. Jagung adalah tanaman musiman dengan masa tanam berkisar antara 80-150 hari, tergantung pada kondisi cuaca. Tahap awal pertumbuhannya bersifat vegetatif, sedangkan tahap menuju panen merupakan fase generatif.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode Penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<div class="line-block">Tahun | Nilai Ekspor | Nilai Ekspor | Produktivitas |<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| US Dollar | US Dollar | Kwintal/Hektar |</div>
<p>|——-|—————–|—————–|—————-| | 2013 | 10.643.000 | 918.890.000 | 67,03 | | 2014 | 13.264.000 | 810.417.000 | 65,02 | | 2015 | 56.365.000 | 696.647.000 | 68,61 | | 2016 | 5.022.000 | 230.923.000 | 70,02 | | 2017 | 1.060.000 | 114.077.000 | 1.118,91 | | 2018 | 72.937.000 | 159.548.000 | 69,26 | | 2019 | 901.000 | 212.684.000 | 67,88 | | 2020 | 16.516.000 | 172.649.000 | 69,64 | | 2021 | 4.235.000 | 297.296.000 | 66,00 | | 2022 | 49.947.000 | 394.458.000 | 66,00 |</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Dalam penelitian ini, metode analisis yang diterapkan mencakup metode kuantitatif dan deskriptif. Analisis kuantitatif melibatkan perhitungan angka-angka untuk mengidentifikasi faktor-faktor yang memengaruhi produktivitas jagung di Sumatra Utara. Sementara itu, metode deskriptif digunakan untuk menyajikan gambaran sistematis dan faktual mengenai dampak ekspor dan impor terhadap produktivitas jagung di Sumatra Utara, dengan mempertimbangkan variabel ekspor, impor, dan produktivitas. Pendekatan kuantitatif diterapkan dengan menerapkan model regresi linier. Secara lebih rinci, model tersebut dapat dijelaskan sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_1+\beta_2 x_2+\mu_t
\]</span> Keterangan : Y = Pertumbuhan Ekonomi</p>
<p><span class="math display">\[x_1\]</span>= Total Ekspor</p>
<p><span class="math display">\[x_2\]</span>= Total Impor</p>
<p><span class="math display">\[u_t\]</span> = Error</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Pada bagian ini dapat ditampilkan data yang telah dikumpulkan :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Metopel/UAS - Fawwazky Raja Putra Kiswandi'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">read_excel</span>(<span class="st">"latihan1.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
          X       Y
      &lt;dbl&gt;   &lt;dbl&gt;
 1 15838850 436188.
 2 17464905 447987.
 3 15385275 448992.
 4 14716275 458769.
 5 18513121 470984.
 6 16527848 482065.
 7 14716275 495607.
 8 17364812 489996.
 9 26755136 506472.
10 27765830 529533.</code></pre>
</div>
</div>
<p>Diketahui : X = Nilai Ekspor Kelapa Sawit Y = PDRB Kota Riau</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data1.xlsx"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>X<span class="sc">+</span>Y, <span class="at">y=</span>S))<span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">'blue'</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Plot Terhadap PDRB Kota Riau"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Nilai Ekspor &amp; Impor"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Produktivitas"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber:  Trade Map &amp; Badan Pusat Statistik"</span>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil pengaruh nilai ekspor terhadap PDRB Kota Riau diestimasi menggunakan regresi univariat. Hasilnya ditunjukkan sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data1.xlsx"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(S<span class="sc">~</span>X<span class="sc">+</span>Y,<span class="at">data=</span>dat)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = S ~ X + Y, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-250.02 -209.42  -18.53   32.62  765.52 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  3.987e+02  2.071e+02   1.925   0.0956 .
X           -3.439e-06  4.289e-06  -0.802   0.4490  
Y           -3.655e-07  3.817e-07  -0.958   0.3702  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 338.9 on 7 degrees of freedom
Multiple R-squared:  0.1914,    Adjusted R-squared:  -0.0396 
F-statistic: 0.8286 on 2 and 7 DF,  p-value: 0.4754</code></pre>
</div>
</div>
<p>Hasil di atas mencerminkan hasil estimasi Ordinary Least Squares (OLS) menggunakan model regresi multivariat. Hasil regresi tersebut dimanfaatkan untuk memahami keterkaitan antara produktivitas jagung di Indonesia (variabel dependen) dengan nilai ekspor dan impor jagung (variabel independen). Berdasarkan hasil regresi, terdapat nilai F sebesar 0.8286 dengan probabilitas sebesar 0.4754. Artinya, tidak terdapat pengaruh signifikan terhadap produktivitas jagung di Indonesia selama periode 2013-2022. Nilai R menunjukkan seberapa besar variabel independen memengaruhi variabel dependen. Koefisien determinasi R sebesar 3,96%, menunjukkan bahwa hanya sebagian kecil dari variasi produktivitas jagung dapat dijelaskan oleh nilai ekspor dan impor, sementara 96,04% sisanya dipengaruhi oleh faktor lain yang tidak dimasukkan dalam penelitian ini.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Keterkaitan antara dampak nilai ekspor dan impor jagung terhadap produktivitas jagung Indonesia selama periode 2013-2022 mengindikasikan adanya hubungan yang kurang signifikan. Hubungan antara produktivitas jagung Indonesia dengan nilai ekspor dan impor jagung tercatat sebagai hubungan yang lemah. Penilaian terhadap dampak nilai ekspor dan impor jagung menunjukkan kecenderungan nilai yang negatif, namun pengaruhnya tidak begitu kuat terhadap produktivitas jagung Indonesia. Oleh karena itu, meskipun terdapat korelasi antara variabel-variabel tersebut, namun dampaknya tidak begitu dominan. Dibutuhkan adanya faktor-faktor lain yang menunjukkan peran penting dalam mengatur produktivitas jagung di Indonesia.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Badan Pusat Statistik. (2022). Retrieved January 14, 2024, from https://sumbar.bps.go.id/indicator/53/58/1/luas-panen-produksi-dan-produktivitas-jagung.html</p>
<p>ITC Trade Map. (2022). Retrieved January 14, 2024, from https://www.trademap.org/</p>
<p>Kementrian Perdagangan. (2014). Profil komoditas. Kementrian Perdagangan, 33. https://ews.kemendag.go.id/sp2kp-landing/assets/pdf/120116_ANK_PKM_DSK_Jagung.pdf</p>
<p>Mughni, M. E. (2017). Pengaruh Variabel Makro Terhadap Produktivitas Jagung Di Indonesia.</p>
<p>Utomo, S. (2012). Dampak impor dan ekspor jagung terhadap produktivitas jagung di Indonesia. Etikonomi, 11(2).</p>
<p>Pertanian, K. (2021). Analisis Kinerja Perdagangan Jagung. Pusat Data Dan Sistem Informasi Pertanian Sekretariat Jenderal Kementerian Pertanian 2021, 5–24.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>